### ISSUE TITLE
update historydag version requirement

### ISSUE THREAD

**Issue by jgallowa07** [matsengrp/gctree#121]
https://github.com/matsengrp/gctree/blob/23a71520af416e5022981d9bf80f9a8511273859/setup.py#L40

should be updated to >= 1.2.0

Before updating the historydag version I was getting
```
Command error:
  Traceback (most recent call last):
    File "/opt/miniconda3/bin/deduplicate", line 5, in <module>
      from gctree.deduplicate import main
    File "/opt/miniconda3/lib/python3.9/site-packages/gctree/__init__.py", line 1, in <module>
      from .branching_processes import CollapsedTree, CollapsedForest  # noqa
    File "/opt/miniconda3/lib/python3.9/site-packages/gctree/branching_processes.py", line 36, in <module>
      sequence_resolutions = hdag.parsimony_utils.standard_nt_ambiguity_map_gap_as_char.get_sequence_resolution_func(
  AttributeError: module 'historydag' has no attribute 'parsimony_utils'
```

**Comment by willdumm** [comment]
Thanks Jared! Sorry about this oversight, I'll re-release the PyPI and conda packages on Monday
