### ISSUE TITLE
Error: Biopython

### ISSUE THREAD

**Issue by jonoave** [matsengrp/gctree#46]
Hi,

This time I encountered a real issue. 

```
scons --inference --outdir=case1/case1_gcTree --input=case1/Sequences_Case_1.txt.out.trim --naiveID=Germline
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
python bin/deduplicate.py case1/Sequences_Case_1.txt.out.trim --countfile case1/case1_gcTree/Sequences_Case_1.txt.out.counts --idmapfile case1/case1_gcTree/Sequences_Case_1.txt.out.idmap --naive Germline > case1/case1_gcTree/Sequences_Case_1.txt.out.phylip
Traceback (most recent call last):
  File "bin/deduplicate.py", line 7, in <module>
    from Bio.Alphabet import generic_dna
  File "/Users/jh/miniconda3/envs/gctree/lib/python3.7/site-packages/Bio/Alphabet/__init__.py", line 21, in <module>
    "Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information."
ImportError: Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information
```

I think this issue is highlighted here : https://github.com/B-UMMI/chewBBACA/issues/65

Cheers.

**Comment by WSDeWitt** [comment]
Thanks for raising this! We're a bit swamped now, but will try to patch soon. For now, a workaround might be to install an older Biopython version.
