### ISSUE TITLE
Default help menu missing

### ISSUE THREAD

**Issue by fabio-t** [matsengrp/gctree#59]
When typing `gctree`, I get a crash:

```
$ gctree 
Traceback (most recent call last):
  File "/home/fabio/.local/bin/gctree", line 8, in <module>
    sys.exit(main())
  File "/home/fabio/.local/lib/python3.8/site-packages/gctree/cli.py", line 748, in main
    args = get_parser().parse_args(arg_list)
  File "/usr/lib/python3.8/argparse.py", line 1780, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/lib/python3.8/argparse.py", line 1812, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib/python3.8/argparse.py", line 2047, in _parse_known_args
    ', '.join(required_actions))
TypeError: sequence item 0: expected str instance, NoneType found
```

Would be nice if instead it showed a description of the subcommands.

**Comment by WSDeWitt** [comment]
This behavior has been improved somewhat:
```bash
$ gctree
usage: gctree [-h] {test,infer,simulate} ...
gctree: error: the following arguments are required: {test,infer,simulate}
```
And with the `-h` or `--help` argument you now get:
```bash
$ gctree -h
usage: gctree [-h] {test,infer,simulate} ...

genotype collapsed tree inference and simulation

optional arguments:
  -h, --help            show this help message and exit

subcommands:
  specify one of these

  {test,infer,simulate}
                        additional help available for each subcommand
    test                run tests on library functions
    infer               likelihood ranking of parsimony trees
    simulate            Neutral, and target selective, model gctree simulation
```
